### ISSUE TITLE
Running list of errors fixed via CI

### ISSUE THREAD

**Issue by rudeboybert** [SCBI-ForestGEO/Dendrobands#41]
- [x] For `2019.01` survey, many had `month` as `NA` instead of 3. Fixed in #39 
- [x] One entry in `2013.01` had `year, month, day` as `NA,NA,NA` #36   
- [x] Tag 121298 had status other than `"alive"` or `"dead"` #59 
- [x] Codes `D`, `Q`, and `G` are undefined (D seems to be an incomplete "dead" code) #42
- [x] Wrong code for dead on the ground #67
- [x] Anomalies #70 
- [x] Anomalies #68 
- [x] Anomaly only detected in retrospect #78

**Comment by rudeboybert** [comment]
CI paper was submitted in January 2022 so we no longer need this https://github.com/SCBI-ForestGEO/continuous_integration/releases/tag/1.0.2
